LIBS += -lcomctl32 \
				-lemergeLib

TARGET = WindowTitleTest
SUFFIX = .exe
OBJS = $(TARGET_DIR)/main.o \
			 $(TARGET_DIR)/TestDialog.o \
			 $(TARGET_DIR)/$(TARGET).res

include ../functions.in
include ../globals.in
include ../applet_globals.in
include ../svn.in
