LIBS += -lshell32 \
				-lcomctl32 \
				-lemergeLib \
				-lgdi32 \
				-lcomdlg32 \
				-lemergeGraphics \
				-lemergeAppletEngine \
				-lemergeBaseClasses

TARGET = emergeMediaCtrl
SUFFIX = .exe

include ../functions.in
include ../globals.in
include ../applet_globals.in
include ../svn.in
