LIBS += -lshell32 \
				-lcomctl32 \
				-lshlwapi \
				-lcomdlg32 \
				-lemergeLib \
				-lemergeGraphics \
				-lemergeAppletEngine \
				-lemergeSchemeEngine \
				-lemergeBaseClasses

TARGET = emergeVWM
SUFFIX = .exe

include ../functions.in
include ../globals.in
include ../applet_globals.in
