LIBS += -lshell32 \
				-lcomctl32 \
				-lshlwapi \
				-lemergeLib \
				-lemergeGraphics \
				-luuid \
				-lcomdlg32 \
				-lgdi32 \
				-lemergeStyleEngine \
				-lemergeBaseClasses

TARGET = emergeLauncher
SUFFIX = .exe

include ../functions.in
include ../globals.in
include ../applet_globals.in
include ../hg_file.in
