LIBS += -lemergeLib \
				-lole32 \
				-luuid \
				-lgdi32 \
				-lcomctl32 \
				-lcomdlg32 \
				-lemergeGraphics \
				-lemergeAppletEngine \
				-lemergeSchemeEngine \
				-lemergeBaseClasses

TARGET = emergeCommand
SUFFIX = .exe

include ../functions.in
include ../globals.in
include ../applet_globals.in
include ../hg_file.in
