LIBS += -lversion -lcomctl32 -lole32 -lshlwapi -lemergeLib -luuid

TARGET = emergeAppletEngine
SUFFIX = .dll
EXPORTS = -DEMERGEAPPLETENGINE_EXPORTS

include ../functions.in
include ../globals.in
include ../lib_globals.in
include ../hg_file.in
