#LIBS += -lversion -lole32 -lemergeLib -lmsimg32 -lgdi32 -lshlwapi

TARGET = emergeIcons
SUFFIX = .dll
EXPORTS = -DEMERGEICONS_EXPORTS

include ../functions.in
include ../globals.in
include ../lib_globals.in
include ../hg_file.in
