TARGET = emergeCore
SUFFIX = .exe
LIBS += -lshell32 \
				-lemergeLib \
				-lemergeBaseClasses \
				-lshlwapi \
				-lole32 \
				-lcomctl32 \
				-luuid \
				-lwinmm \
				-lcomdlg32 \
				-lpsapi \
				-ladvapi32

include ../functions.in
include ../globals.in
include ../applet_globals.in
include ../hg_file.in
