LIBS += -lemergeLib -lcomctl32 -lcomdlg32 -lemergeAppletEngine -lemergeBaseClasses

TARGET = emergeHotkeys
SUFFIX = .exe

include ../functions.in
include ../globals.in
include ../applet_globals.in
include ../hg_file.in
