LIBS += -lemergeLib -luuid -lole32 -lemergeAppletEngine -lemergeBaseClasses

TARGET = Explorer
SUFFIX = .exe

include ../functions.in
include ../globals.in
include ../applet_globals.in
include ../hg_file.in
