LIBS += -lshell32 \
				-lcomctl32 \
				-lemergeLib \
				-lemergeGraphics \
				-lemergeAppletEngine \
				-lemergeSchemeEngine \
				-lemergeBaseClasses

TARGET = emergeTasks
SUFFIX = .exe

include ../functions.in
include ../globals.in
include ../applet_globals.in
