LIBS += -lshell32 \
				-lemergeLib \
				-lshlwapi \
				-lole32 \
				-lcomctl32 \
				-lemergeGraphics \
				-lemergeAppletEngine \
				-lemergeBaseClasses \
				-luuid \
				-lwinmm \
				-lcomdlg32

TARGET = emergeWorkspace
SUFFIX = .exe

include ../functions.in
include ../globals.in
include ../applet_globals.in
include ../hg_file.in
