LIBS += -luuid \
				-lole32 \
				-lcomctl32 \
				-lemergeLib \
				-lemergeGraphics \
				-lemergeSchemeEngine \
				-lemergeBaseClasses

TARGET = emergeTray
SUFFIX = .exe

include ../functions.in
include ../globals.in
include ../applet_globals.in
include ../hg_file.in
